final doctorMapList = [
  {
    "name": "David Kemp",
    "type": "Fitness trainer",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image":"assets/doctor.png",
    "description": "I'm here to guide you through the exhilarating world of fitness, where sweat becomes your best friend, and each drop propels you closer to your health and wellness goals.",
  },
  {
    "name": "katthy Mathews",
    "type": "Athletic trainer",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image":"assets/doctor_4.png",
    "description": "I'm your dedicated guide on this dynamic journey, where we'll push the boundaries of what your body and mind can achieve. ",
  },
  {
    "name": "DR. Morris",
    "type": "Exercise specialist",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image":"assets/doctor_3.png",
    "description": "Welcome to a world where every movement is purposeful and every exercise is a step towards optimal well-being! As your exercise specialist, my mission is to tailor a fitness experience that aligns seamlessly with your unique goals and aspirations.",
  },
  {
    "name": "Dr. Bruce Banner",
    "type": "Lifestyle coach",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image":"assets/doctor_1.png",
    "description": "Step into a world of holistic well-being and positive transformation! I'm here to guide you as your lifestyle coach, navigating the intricate dance between your daily choices and your overall health and happiness. ",
  }
];
